using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Recert.IO
{
    public enum State
    {
        Alabama = 0,
        Alaska = 1,
        Arizona = 2,
        Arkansas = 3,
        California = 4,
        Colorado = 5,
        Connecticut = 6,
        Delaware = 7,
        Florida = 8,
        Georgia = 9,
        Hawaii = 10,
        Idaho = 11,
        Illinois = 12,
        Indiana = 13,
        Iowa = 14,
        Kansas = 15,
        Kentucky = 16,
        Louisiana = 17,
        Maine = 18,
        Maryland = 19,
        Massachusetts = 20,
        Michigan = 21,
        Minnesota = 22,
        Mississippi = 23,
        Missouri = 24,
        Montana = 25,
        Nebraska = 26,
        Nevada = 27,
        NewHampshire = 28,
        NewJersey = 29,
        NewMexico = 30,
        NewYork = 31,
        NorthCarolina = 32,
        NorthDakota = 33,
        Ohio = 34,
        Oklahoma = 35,
        Oregon = 36,
        Pennsylvania = 37,
        RhodeIsland = 38,
        SouthCarolina = 39,
        SouthDakota = 40,
        Tennessee = 41,
        Texas = 42,
        Utah = 43,
        Vermont = 44,
        Virginia = 45,
        Washington = 46,
        WestVirginia = 47,
        Wisconsin = 48,
        Wyoming = 49,
        AmericanSamoa = 50,
        DistrictOfColumbia = 51,
        FederatedStatesOfMicronesia = 52,
        Guam = 53,
        MarshallIslands = 54,
        NorthernMarianaIslands = 55,
        Palau = 56,
        PuertoRico = 57,
        VirginIslands = 58
    }
}
